### ISSUE TITLE
videos not being removed

### ISSUE THREAD

**Issue by brysin** [EvNaverniouk/youtube-hide-watched#2]
videos are no longer being removed from my sub box. when i opened up the script and try to reload and run it it gave me an error saying this

/*
Exception: ReferenceError: GM_addStyle is not defined
@Scratchpad/4:21:5
@Scratchpad/4:19:2
*/

**Comment by EvNaverniouk** [comment]
What browser and what version of Greasemonkey are you using?

**Comment by brysin** [comment]
firefox version 47.0.1

**Comment by brysin** [comment]
and greasemonkey version 3.8

**Comment by brysin** [comment]
i just went to a youtuber's video page and for some reason it still works there but not on the sub box

**Comment by EvNaverniouk** [comment]
What is the YouTube URL for the "sub box area"?

**Comment by brysin** [comment]
what do you mean

**Comment by EvNaverniouk** [comment]
I'm not sure I understand what you mean by "sub box". Can you help me find this area?

**Comment by brysin** [comment]
on my subscriptions page videos are not being hidden (youtube.com/feed/subscriptions)
however one channel i went to (this url https://www.youtube.com/channel/UCO5KTtyzcJK2R4VUhsCVYUQ/videos) is hiding videos, sorry i dont know very much about this

**Comment by brysin** [comment]
its working now
