### ISSUE TITLE
No longer working as 20 Nov (New Progress Bar)

### ISSUE THREAD

**Issue by QuDubz** [EvNaverniouk/youtube-hide-watched#3]
No longer working after youtube added a new red "Progress bar" to videos.

http://i.imgur.com/iegRPCD.gif

All videos that has a small red bar has already been watched, but are not hidden.

**Comment by EvNaverniouk** [comment]
Thanks. Will try to fix soon.

**Comment by idelsink** [comment]
Perhaps you can look at the bar and use the percentage and a parameter to mark them as "watched" and hide them? 
`0` would mean "mark watched when this bar is present" and the rest is just from the minimal percentage set in the parameter.

E.g. this can be used then:

```html
<span class="resume-playback-progress-bar" style="width:12%"></span>
```

**Comment by EvNaverniouk** [comment]
Published 0.7. Should be fixed now.

**Comment by idelsink** [comment]
Just tested it and it seems to working fine. 
Still the idea of some progress/percentage parameter would be a nice touch. :)

**Comment by EvNaverniouk** [comment]
Sure, Ill open a new issue to track that.
