### ISSUE TITLE
Issues with Greasemonkey under Firefox.

### ISSUE THREAD

**Issue by Moycakes** [EvNaverniouk/youtube-hide-watched#6]
Since the Dec02 update, this script hasn't worked, so I've been using an older version until I had the time to figure out why it wasn't functional.  The debug console is spammed with '$ is undefined', so I figured it was an issue loading jQuery.

I pasted the jQuery source above the script, and modified the addJQuery function, and it seems to be functional now.  I'm assuming this is a Greasemonkey thing.

(Including a library that large for getting the width of an element seems over kill to me.)

**Comment by EvNaverniouk** [comment]
Pushed a fix in version 1.3
