### ISSUE TITLE
the script again does not work

### ISSUE THREAD

**Issue by wrexwaz** [EvNaverniouk/youtube-hide-watched#7]
if Dan Pollock's hosts file is turn on in ublock addon
Firefox 51, greasemonkey, 
i dont know witch exception i must add to list 
i dont want to turn off whole Dan Pollock's list :/

**Comment by EvNaverniouk** [comment]
Hmm. I cannot reproduce. It's working for for me on Firefox 51.

**Comment by wrexwaz** [comment]
​
​

2017-02-25 23:30 GMT+01:00 Evgueni Naverniouk <notifications@github.com>:
